language: python
language: go
python:
  - "3.6"
go:
  - "1.10"
go_import_path: github.com/ucbdrive/sat
before_install:
  - sudo apt-get update
  - sudo apt-get install -y npm
install:
  - sudo pip install --upgrade pip
  - sudo pip install pycodestyle
  - go get github.com/aws/aws-sdk-go github.com/mitchellh/mapstructure gopkg.in/yaml.v2 github.com/satori/go.uuid
  - npm install
  - node_modules/.bin/flow-typed install jest jquery lodash
script:
  - pycodestyle --show-source . --exclude=node_modules
  - node_modules/.bin/eslint .
  - node_modules/.bin/flow check
  - node_modules/.bin/npx webpack --config webpack.config.js --mode=production
  - go build -i -o ./bin/sat ./server/http
  - go test ./server/http -args --config ../../app/config/travis_config.yml
  - npm test
